# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Parth Modi
tagline:             'Ruby and Rails | Python | ReactJS | Cybersecurity'
description:         'Specializes in building various kind of applications with strong focus on backend technologies such as Ruby on Rails, Python.'
url:                 "https://parthrmodi.com"
baseurl:             "/blog"
paginate:            5
excerpt_separator:   <!--more-->
date_format:         "%B %d, %Y"

exclude: [vendor]

# About/contact
author:
  name:              Parth Modi
  url:               https://twitter.com/8parth
  email:             "parthmodi54@yahoo.com"
  avatar           : "public/assets/bio-photo.jpg"
  bio              : "Technical Lead | Ruby and Rails | Python | ReactJS | Cybersecurity"
  location         : "Ahmedabad, India"
  email            : "parthmodi54@yahoo.com"
  codepen          : #"parthmodi"
  facebook         : "parth.modi.359"
  github           : "8parth"
  google_plus      : "115885247380801217391"
  linkedin         : "parthrmodi"
  stackoverflow    : "4933185/parth-modi"
  twitter          : "ParthModi08"

# jekyll-seo-tag
twitter:
  username: ParthModi08
social:
  name: Parth Modi
  links:
    - https://twitter.com/ParthModi08
    - https://www.facebook.com/parth.modi.359
    - https://www.linkedin.com/in/parthrmodi/
    - https://plus.google.com/115885247380801217391
    - https://github.com/8parth
webmaster_verifications:
  google: "UA-77740680-2"
  bing: "401CF93354E92FF91A4131D01853C962"
  # alexa:
  # yandex:

analytics:
  google:
    tracking_id: "UA-77740680-2"

feed:
  path: atom.xml
  url: "https://parthrmodi.com/blog/"

jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
    category: archive-categories
    tag: archive-tags

comments:
  provider: "disqus"
  disqus:
    shortname: "parthrmodi-com"

defaults:
    values:
      comments: true
      share: true
related: true

# gems
plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-archives
  - jekyll-seo-tag
  - jemoji
  - jekyll-sitemap

# collections
collections:
  presentations:
    output: true
    permalink: /presentations/:name
